---

- hosts: localhost
  vars:
    gitlab_runner_executor: "shell"
    gitlab_runner_ci_server_url: https://gitlab.com/
    gitlab_runner_registration_token: b6jR_DnMjMSWVExkhjX1
    gitlab_runner_name: my-gitlab-runner
    gitlab_runner_tag_list:
      - "{{ gitlab_runner_name }}"
    gitlab_runner_register_run_untagged: "false"
  roles:
    - egeneralov.gitlab-runner
