---


- name: System-wide deps
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - debian-archive-keyring
      - python-pip
    update_cache: yes
    cache_valid_time: 3600
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2


- name: import key
  apt_key:
    url: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey"
  register: key
  until: key is success
  retries: 3
  delay: 2


- name: import repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main"
    filename: gitlab
  register: repo
  until: repo is success
  retries: 3
  delay: 2


- name: "apt-get install -yq gitlab-runner"
  apt:
    name: gitlab-runner
    update_cache: "{% if key is changed or repo is changed %}yes{% else %}no{% endif %}"
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2


- name: "Register runner"
  shell: "/usr/bin/gitlab-runner register"
  environment:
    REGISTER_NON_INTERACTIVE: "true"
    DOCKER_IMAGE: "{{ gitlab_runner_docker_default_image }}"
    CONFIG_FILE: "{{ gitlab_runner_config_file }}"
    RUNNER_TAG_LIST: "{{ gitlab_runner_tag_list|join(',') | quote }}"
    REGISTRATION_TOKEN: "{{ gitlab_runner_registration_token }}"
    REGISTER_RUN_UNTAGGED: "{{ gitlab_runner_register_run_untagged }}"
    REGISTER_LOCKED: "{{ gitlab_runner_register_locked }}"
    RUNNER_NAME: "{{ gitlab_runner_name }}"
    RUNNER_REQUEST_CONCURRENCY: "{{ gitlab_runner_request_concurrency | quote }}"
    CI_SERVER_URL: "{{ gitlab_runner_ci_server_url }}"
    CI_SERVER_TOKEN: "{{ gitlab_runner_ci_server_token }}"
    CI_SERVER_TLS_CA_FILE: "{{ gitlab_runner_ci_server_tls_ca_file }}"
    CI_SERVER_TLS_CERT_FILE: "{{ gitlab_runner_ci_server_tls_cert_file }}"
    CI_SERVER_TLS_KEY_FILE: "{{ gitlab_runner_ci_server_tls_key_file }}"
    RUNNER_EXECUTOR: "{{ gitlab_runner_executor }}"
    RUNNER_BUILDS_DIR: "{{ gitlab_runner_builds_dir }}"
    RUNNER_PRE_CLONE_SCRIPT: "{{ gitlab_runner_pre_clone_script }}"
    RUNNER_PRE_BUILD_SCRIPT: "{{ gitlab_runner_pre_build_script }}"
    RUNNER_POST_BUILD_SCRIPT: "{{ gitlab_runner_post_build_script }}"


- name: fix output_limit
  lineinfile:
    path: /etc/gitlab-runner/config.toml
    line: "  output_limit = 16980"
    insertafter: "[[runners]]"
  register: trg_output


- name: fix concurrent
  lineinfile:
    path: /etc/gitlab-runner/config.toml
    line: "concurrent = {{ gitlab_runner_request_concurrency }}"
    regexp: "concurrent.*"
  register: trg_concurrent


- name: restart runner
  systemd:
    name: gitlab-runner
    state: restarted
  when: trg_concurrent is changed or trg_output is changed
